### ISSUE TITLE
Phantomjs

### ISSUE THREAD

**Issue by joe-eklund** [enkur/ATT-Fiber-Check#1]
When I run speecheck.py I get the following error:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 
```
There are a lot more errors that seem redundant after this that I have linked in at the bottom of this post.
Any ideas? I haven't used phantomjs before so I'm not really sure.

I'm running in a venv and ran the pip installs referenced in the readme. 

Running under:
Ubuntu 16.10
Python 3.5.2+
pip (9.0.1)
pkg-resources (0.0.0)
pygeocoder (1.2.5)
requests (2.13.0)
selenium (3.0.2)
setuptools (26.1.1)
splinter (0.7.5)

Here is the full error text:

```
(att) joe@mirkwood:~/projects/playground/ATT-Fiber-Check$ python speedcheck.py 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment


Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e2400>>

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedcheck.py", line 25, in test
    browser = Browser('phantomjs')
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/splinter/driver/webdriver/phantomjs.py", line 38, in __init__
    self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "speedcheck.py", line 68, in do_stuff
    run_test(q.get())
  File "speedcheck.py", line 64, in run_test
    test(street, city, zip)
  File "speedcheck.py", line 57, in test
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e2cc0>>

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e2a58>>
Traceback (most recent call last):
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e2b38>>
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e27b8>>
Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
Traceback (most recent call last):
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f8dec7e2eb8>>
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
Traceback (most recent call last):
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
Traceback (most recent call last):
    self.stop()
    self.stop()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
    self.stop()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
    self.stop()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    self.stop()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    self.stop()
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    if self.process is None:
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
AttributeError: 'Service' object has no attribute 'process'
    if self.process is None:
    if self.process is None:
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
AttributeError: 'Service' object has no attribute 'process'
AttributeError: 'Service' object has no attribute 'process'
    if self.process is None:
  File "/home/joe/projects/envs/att/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
AttributeError: 'Service' object has no attribute 'process'
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
^X^CTraceback (most recent call last):
  File "speedcheck.py", line 84, in <module>
    q.join()
  File "/usr/lib/python3.5/queue.py", line 83, in join
    self.all_tasks_done.wait()
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by enkur** [comment]
You have to download the phantomjs web driver from here and install it in
your python path.
http://phantomjs.org/download.html

hope that helps.

**Comment by joe-eklund** [comment]
Thanks! I will give that a shot and let you know.

**Comment by joe-eklund** [comment]
I was able to get it installed and that fixed my problems.
